### ISSUE TITLE
Spring IO Platform 2.0 対応の内容をガイドラインへ反映する

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#1305]
## Description

5.1.0でSpring IO Platform 2.0 に対応する予定なので、ガイドラインへも変更内容を取り込む。

フレームワークスタックのライブラリのバージョンアップ状況は、[こちら](https://github.com/terasolunaorg/terasoluna-gfw/issues/362#issuecomment-128600621) を参照。

* Spring 4.1 -> 4.2
* Spring Security 3.2 -> 4.0
* Spring Data Commons 1.9 -> 1.11
* Hibernate Validator 5.1 -> 5.2
* Jackson 2.4 -> 2.6
* Joda-Time 2.5 -> 2.8

辺りがメインどころだと思われる。

5.0.0.RELEASEで対応を見送ったSpring 4.0 + 4.1の変更点も反映候補に含める。

* #887 

## Possible Solutions

本issueでは以下のタスクを行う。

* フレームワークスタックにしているライブラリの更新内容の調査 (terasolunaorg/terasoluna-gfw#362)
* 既存ガイドラインの更新対象(Update or Delete)の洗い出し
* 機能追加などのガイドラインへの反映要否の判断

実際の修正は、サブissueを発行して対応する予定。

- [ ] #1490 (Support `ResponseBodyAdvice` and `RequestBodyAdvice`)
- [ ] #996 (Update Excel downloading)
- [ ] #1493 (Update warning for message definition bugs of Hibernate Validator)
- and more ...

## Affects Version/s
\-

## Fix Version/s
- [ ] 5.1.0

## Issue Links
* terasolunaorg/terasoluna-gfw#362
* #887

**Comment by kazuki43zoo** [comment]
@btokadanob , @iwanagah , @btyoshikawaa 

5.0.0リリース時に対応を見送ったSpring 4.0 + 4.1の変更も対応候補に含める。
候補は #887 を参照。

**Comment by making** [comment]
https://github.com/terasolunaorg/guideline/issues/996 も忘れずに。

**Comment by iwanagah** [comment]
https://github.com/terasolunaorg/guideline/issues/887 で見送った@JsonViewについて
https://github.com/terasolunaorg/guideline/issues/1490 で対応する。

**Comment by iwanagah** [comment]
各issueで管理するので、全体のこのissueはクローズ。
