### ISSUE TITLE
Investigate WebLogic 12c R2 (12.2.1-Full Java EE 7)

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1393]
## Description
WebLogic 12c R2(12.2.1) has been released.
12c R2 provide full Java EE 7 environment.

## Possible Solutions
Investigate about 12c R2(12.2.1) and reflect changes to the guideline if needed.

Candidates are:

- [x] Garbled problem is resolved in "File Upload functionality" (at #1522)
- [x] Bean Validation 1.1 instead of 1.0 (Conflict library problem is resolved at https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/383) 
- [x] JPA 2.1 instead of 2.0 (Conflict library problem is resolved at https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/383)
- [x] JAX-WS 2.2 (Plan to support in guideline since 5.1.0 at #1340)
- [x] JavaMail 1.5 instead of 1.4 (Plan to support in guideline since 5.1.0 at #1165)
-  JMS 2.0 instead of 1.1 ~~(Plan to support in guideline since 5.1.0)~~ scope out
- Servlet 3.1 instead of 3.0
* JSP 2.3 instead of 2.2
* EL 3.0 instead of 2.2
* JTA 1.2  instead of 1.1
* etc ...

## Affects Version/s
N/A

## Fix Version/s
- [ ] 5.1.0

## Issue Links
* http://www.oracle.com/technetwork/middleware/weblogic/downloads/index.html
* https://jira.spring.io/browse/SPR-13234
* http://www.oracle.com/technetwork/middleware/fusion-middleware/documentation/fmw-1221certmatrix-2739738.xlsx
* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/383

**Comment by btshimizukza** [comment]
I've tried file upload using servlet standard functionality. Garbled problem has been resolved in this version !!

**[Environment Informations]**
**OS** : Windows 7 enterprise (64bit)
**Java** : Oracle JDK 1.8.0_51
**Installer** : Quick Installer intended for Oracle WebLogic Server and Oracle Coherence development only. (211 MB)

**Comment by ikeyat** [comment]
Second and third checkbox are to update if it is possible to remove following settings for libraries conflict.
https://github.com/terasolunaorg/terasoluna-gfw/wiki/WebLogic_ja#weblogicxml%E3%81%AE%E8%BF%BD%E5%8A%A0

**Comment by ikeyat** [comment]
It will be fixed with the technic https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/383
I close this.
