### ISSUE TITLE
[English Translation] 5.5 Validation

### ISSUE THREAD

**Issue by btdaruwanib** [terasolunaorg/guideline#241]
- [ ] Reflected #320(#493) in English version.
- [ ] Reflected #549(#580) in English version.
- [ ] Reflected #560(#582) in English version.
- [ ] Reflected #766(#796) in English version.
- [ ] Reflected #296(#806) in English version.

**Comment by kazuki43zoo** [comment]
英語化のとりまとめissueは一旦廃止。
