### ISSUE TITLE
Spring Framework 4対応の内容をガイドラインに反映

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#482]
[Spring Framework 4対応(IO Platform化対応)](terasolunaorg/terasoluna-gfw#132)の内容をガイドラインに取り込む。
see terasolunaorg/terasoluna-gfw#132.

**[All]**
- [x] Update framework stack(library list) for Spring IO platform 1.0.2.RELEASE. (#544)
- [x] Update framework stack(library list) for Spring IO platform 1.0.3.RELEASE. see [here](https://github.com/terasolunaorg/terasoluna-gfw/issues/218). (#569)
- [x] Update framework stack(library list) for Spring IO platform 1.1.0.RELEASE. see [here] (https://github.com/terasolunaorg/terasoluna-gfw/issues/205). (#659)
- [x] Update framework stack(library list) for Spring IO platform 1.1.1.RELEASE. see [here] (https://github.com/terasolunaorg/terasoluna-gfw/issues/205).  (#727)
- [x] Apply in SpringMVCOverview. (#615)
- [x] Modify URLs to refer to official document. (#711)

**[Modify word or phrase or sentence]**
- [x]  `Spring 3 Type Conversion -> Spring Type Conversion` in ApplicationLayer.rst (#711)
- [x] `Spring 3 Field Formatting -> Spring Field Formatting` in ApplicationLayer.rst (#711)

**[Spring / Required task]**
- [x] add some attributes in `@ControllerAdvice`(#549)
- [x] add `@RestController` (#560)
- [x] support JTA1.2 (add note about `@Transactional`) (#562)
- [x] modify description of CSRF on Spring4 + Spring Security 3.2 (#563)
- [x] modify description of Spring Data (Common) (#592)
- [x] add builder style method in `ResponseEntity` (from 4.1) (#561)
- [x] add mvc xml namespace for `ViewResolver` (from 4.1) (#609)

**[Spring / Optional task (If needed)]**
- support `@JsonView`(and `ResponseBodyAdvice`) -> not apply in this release(5.0.0)
- [x] support `-parameters` of Java8 (#613)
- support control @ModelAttribute 's order -> not apply in this release(5.0.0)
- add mvcUrl as jsp tag library -> not apply in this release(5.0.0)
- add mvc xml namespace(<mvc:path-matching>) -> not apply in this release(5.0.0)
- support version of itext on spring 4 in FileDownload.rst ? -> not support in this release(5.0.0)

**[Spring / Optional task (If there are time)]**
- improve static resource handling(<mvc:resources>) -> not apply in this release(5.0.0)
- improve view controller -> not apply in this release(5.0.0)

**[Common library]**
- [x] modify common library (`CompositeRequestDataValueProcessor ` and `RequestDataValueProcessorAdaptor `)  (#564)

**[Other]**
- [x] use Tiles 3 instead of 2 (#502)
- [x] use Jackson 2 instead of 1 (#503)
- [x] use Joda-Time 2.5 instead of 2.2 (`DateMidnight` is deprecated) (#553)
- [x] use commons-dbcp2 instead of commons-dbcp (#554)
- [x] use Bean Validation 1.1 (Hibernate Validator 5.x) instead of Bean Validation 1.0 (Hibernate Validator 4.x) (#555)
- [x] use JPA 2.1 (Hibernate ORM 4.3.x) instead of JPA 2.0 (Hibernate ORM 4.2.x) (#556)
- [x] update description of `@Transactional(readOnly = true)` for JPA (reflect [SPR-8959](https://jira.spring.io/browse/SPR-8959))

**[Translate to English]**
- [x] #502 (同時に対応)
- [x] #503 (同時に対応) 
- #544 + #569 + #659 + #727 (一部同時に対応)  -> Moved to #886 
- #549 (#580, #620, #758 )  -> Moved to #886 
- [x] #553
- [x] #554 (同時に対応)
- #555 (一部同時に対応)  -> Moved to #886 
- #556  -> Moved to #886 
- #560 (#582, #622)  -> Moved to #886 
- #561  -> Moved to #886 
- #562  -> Moved to #886 
- #563  -> Moved to #886 
- #592  -> Moved to #886 
- #609  -> Moved to #886 
- [x] #613 (同時に対応)
- [x] #615 (同時に対応)
- [x] #711 (同時に対応)
- [x] #561(#755) (同時に対応)

**Comment by btshimizukza** [comment]
日本語版への反映は完了。

* 先送りにした対応のissue
* 英語版への反映issue

の発行を行いcloseする。

**Comment by btshimizukza** [comment]
先送り対応の検討issueと英語化issueを発行したのでclose.
