### ISSUE TITLE
Add user manual about jsp tag & el functions provided by common library

### ISSUE THREAD

**Issue by making** [terasolunaorg/guideline#497]
Add user manual about jsp tag & el functions provided by common library as a new page in Appendix.

- [x] Added the Japanese version #614
- [x] Backported to 1.0.x line (Japanese)  #617 
- [ ] Translated to the English version  #618
- [ ] Backported to 1.0.x line (English)

**Comment by btshimizukza** [comment]
Close because raised a issue for translation. #618
