### ISSUE TITLE
[Spring IO platform対応] Bean Validation(Hibernate Validator)のバージョンアップ内容をガイドラインに反映する

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#555]
Spring4対応(#482)に伴い、Bean Validationのバージョンを1.1(Hibernate Validator 5系)にする。

**Bean Validation 1.1の変更点を反映する。**
- [x] JSR-303という表現をなくす。(Bean Validation or Bean Validation 1.1 という表現に変更) (#594)
- [x] 非推奨になったAPI（`ConstraintViolationBuilder#addNode`）を使用する例を修正する。( #601)
- [x] `@DecimalMin` と `@DecimalMax` に `inclusive` 属性が追加になった事を反映する。 (#600)
- [x] アプリケーション実行時にELのAPIが必要になった点と、Junitなどのスタンドアロン環境でBean Validationを使用する場合にEL2.2以上のAPI実装が必要になる点を言及する(EL2.2以上が必要なのは、Hibernate Validatorの実装に依存している)。(#603)
- [x] メッセージにEL式が使えるようになった事を紹介する。 (#604)
- メソッドバリデーションをSpring Framework上で適用する方法をAppendixに追加する。 #624 
  -> 1.1.0での対応を見送ったため、別issues(#708)で対応する    

**Hibernate Validator 5.x系(Spring IO platform 1.1の依存バージョン)の変更点を反映する。**
- [x] Hibernate Validatorのバージョンに依存する記載とURLを変更 (#599)
- [x] Hibernate独自の制約アノテーションにいくつか変更点があるので、必要なものについてはガイドラインへ反映する。 (#600)
- [x] Hibernate Validator がデフォルトで用意する `ValidationMessages.properties` の変更内容を反映する。 (#600)
- [x] Hibernate Validator 5.1.xのバグ情報を記載する (https://github.com/terasolunaorg/terasoluna-gfw/issues/205#issuecomment-64752586) (#600)
- [x] REST編に、`ValidationMessages.properties` にメッセージを定義するサンプルがあるので、5.1系のメッセージ定義にあわせて修正する。 #640 

**英語化**

- [x] #594 (同時に対応)
- #600 -> Moved to #885 
- [x] #601 (同時に対応) 
- #603 -> Moved to #885
- #604 -> Moved to #885
- [x] #640  (同時に対応)

**Comment by btshimizukza** [comment]
英語化issueを発行したのでclose.
