### ISSUE TITLE
Reflect dependency libraries version up  to English version(for 5.0.0)

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#586]
Reflect to FrameworkStack.rst (#201)

- [x] Update framework stack(library list) for Spring IO platform 1.0.2.RELEASE. (#544)
- [x] Update framework stack(library list) for Spring IO platform 1.0.3.RELEASE. see here. (#569)
- [x] Update framework stack(library list) for Spring IO platform 1.1.0.RELEASE. see here. (#659)
- [x] Update framework stack(library list) for Spring IO platform 1.1.1.RELEASE. see here. (#727)
- [x] Update `net.sf.dozer:dozer` (5.4.0 -> 5.5.1) in FrameworkStack (#570)
- [x] Update(Add) `net.sf.dozer:dozer-spring` (5.5.1)  in FrameworkStack  (#570)
- [x] Update `org.jadira.usertype:usertype.core` (3.0.0.GA -> 3.2.0.GA)  in FrameworkStack (#571)
- [x] Update `org.jadira.usertype:usertype.spi` (3.0.0.GA -> 3.2.0.GA)  in FrameworkStack (#571)

**Comment by btshimizukza** [comment]
resolve via #829 .
