### ISSUE TITLE
Apply bug fix of terasolunaorg/terasoluna-gfw#256

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#766]
see terasolunaorg/terasoluna-gfw#256 .

Related Issues : #648 

- [x] Apply to Validation.rst #788 
- [x] Apply to CodeList.rst #789 
- [x] Apply to TutorialREST/index.rst #787

**Comment by btshimizukza** [comment]
master, 1.0.xへの反映＋英語化issueを発行したのでクローズする。
