### ISSUE TITLE
Update change log for 1.0.2

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#804]
- [x] Add change logs into Japanese version #816 
- [x] Add change log of TagLibAndELFunctions.rst #819 
- [x] Add change logs into English version
- [x] Add change logs of #846 & #255 
- [x] Modify "update date"

Translation issue moved to #894 .

**Comment by btshimizukza** [comment]
英語化issueを発行したためclose.
